[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[forms]]
  name = "newsletter"
  
  [forms.notifications]
    [forms.notifications.email]
      to = "info@gatewaytoaloha.com"
      from = "no-reply@gatewaytoaloha.com"
      subject = "New Newsletter Subscription!"
      template = """
      New newsletter subscriber!
      
      Email: {{.email}}
      Signup Date: {{.signup-date}}
      
      View all submissions in your Netlify dashboard:
      {{.SiteURL}}/admin/forms/newsletter
      """

[[forms]]
  name = "vacation-planner"
  
  [forms.notifications]
    [forms.notifications.email]
      to = "info@gatewaytoaloha.com"
      from = "no-reply@gatewaytoaloha.com"
      subject = "New Vacation Planning Request!"
      template = """
      New vacation planning request received!
      
      Name: {{.name}}
      Email: {{.email}}
      Phone: {{.phone}}
      Travel Dates: {{.travel_dates}}
      Number of Travelers: {{.travelers}}
      Islands: {{.islands}}
      Travel Style: {{.travel_style}}
      Planning Option: {{.planning_option}}
      Interests: {{.interests}}
      Notes: {{.notes}}
      
      View all submissions in your Netlify dashboard:
      {{.SiteURL}}/admin/forms/vacation-planner
      """